let infile='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasssssssssssssssssssssssssrrrrrrrrrrrraaaaaaaaaaaaassssssssssssssrrrrrreeeee
			eeeeeeeennnnnnnnnnnnnnnnsssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnnnnnnnnnnnnssssssssssaaaaaaaaaaannnnneneneneneeneenenaaaaaasssssssss';
console.log(infile.length);
